export const Add_To_Cart = "Add_To_Cart"
export const Remove_To_Cart  = "Remove_To_Cart"
export const Empty_Cart = "Empty_Cart"
export const Product_List ="Product_List"
export const Set_Product_List = "Set_Product_List"